[project]
name = "keycloak-fetch-bot"
version = "0.0.1"
authors = [
    {name = "Cesar Valdez"}
]
description = "Export data from KeyCloak server"
keywords = [
    "KeyCloak"
]
requires-python = ">=3.8"

dependencies = [
    "kcapi>=1.0.24",
    "importlib_resources",
]

[project.urls]
repository = "https://github.com/cesarvr/keycloak-fetch-bot"

[project.scripts]
kcfetcher = "kcfetcher.main:main_cli"
kcfetcher_save_token = "kcfetcher.main:main_token_save_to_file"

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]   # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []
include-package-data = true

[tool.setuptools.package-data]
"kcfetcher.data" = ["kcfetcher_blacklist"]

[tool.black]
line-length = 160
target_version = ['py38']

[tool.pytest.ini_options]
# minversion = "2.0"
pythonpath = [
  "."
]
